
  - name: include playbook for removing Percona repo
    include: remove_percona_repository.yml

  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_0.1-6.{{ansible_lsb.codename}}_all.deb
    when: ansible_os_family == "Debian"

  - name: add the Percona main deb repo
    apt_repository: repo='deb http://repo.percona.com/apt {{ ansible_lsb.codename }} main' state=present update_cache=yes
    when: ansible_os_family == "Debian"

  - name: add the main Percona yum repos for centos 6 and 7
    yum: name=https://www.percona.com/redir/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm
    when: ansible_os_family == "RedHat" 
