  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: add the Percona testing yum repos for centos 6 and 7
    yum: name=https://repo.percona.com/yum/percona-release-0.1-10.noarch.rpm
    when: ansible_os_family == "RedHat" 

  - name: enable the tools testing repo
    command: percona-release enable-only tools testing
