# This task installs PSMDB 3.6
#

  - name: install Percona Server for MongoDB 3.6 new deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-server-mongodb-36
      - percona-server-mongodb-36-dbg
    when: ansible_os_family == "Debian"

  - name: install Percona Server for MongoDB 3.6 new rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - Percona-Server-MongoDB-36
      - Percona-Server-MongoDB-36-debuginfo
    when: ansible_os_family == "RedHat"
