---
# This playbook enables the percona repo and installs packages for all products

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: Install percona repository package for debian
    apt:
      deb: https://repo.percona.com/apt/pool/testing/p/percona-release/percona-release_1.0-14.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: Install percona repository package for redhat/centos
    yum: name=https://repo.percona.com/yum/testing/latest/RPMS/noarch/percona-release-1.0-14.noarch.rpm
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 6

  - name: Install epel 7 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: Install epel 6 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: Install epel 8 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: enable ps80 repo
    command: percona-release enable ps-80

  - name: enable testing repo
    command: percona-release enable original testing

  - name: disable the mysql module on RHEL/CentOS 8
    command: /usr/bin/dnf module disable mysql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Update cache for debian
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

# Install PXB packages
  - include_tasks: install_pxb.yml

# Install PS packages
  - include_tasks: install_ps.yml

# Install PXC packages
  - include_tasks: install_pxc.yml

# Install PT packages
  - include_tasks: install_pt.yml

# Install Proxysql packages
  - include_tasks: install_proxysql.yml

# Install PMM packages
  - include_tasks: install_pmm.yml

# Install Plugins packages
  - include_tasks: install_plugins.yml

# Install PSMDB packages
  - include_tasks: install_psmdb.yml
