---
# This playbook sets up the mongodb-org repo and installs mongodb

- hosts: all
  name: Prepare a clean machine with percona (and EPEL) repo(s) installed
  become: true
  become_method: sudo

  tasks:
  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/pool/testing/p/percona-release/percona-release_1.0-17.generic_all.deb
#     deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: fix jessie repos
    template: src=../templates/jessie.repo
              dest=/etc/apt/sources.list
              mode=0640 owner=root group=root
    when: ansible_os_family == "Debian" and ansible_distribution_release == "jessie"

  - name: install deb packages 
    apt: 
      name: "{{ packages }}"
      update_cache: yes
    vars: 
      packages:
      - vim
    when: ansible_os_family == "Debian"

  - name: epel 6 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: epel 7 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: setup epel 7 repo for Amazon Linux 2
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

  - name: epel 8 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: add the yum percona repos
    yum: name=https://repo.percona.com/yum/testing/latest/RPMS/noarch/percona-release-1.0-16.noarch.rpm
#   yum: name=https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    when: ansible_os_family == "RedHat"

  - name: install packages in centos
    yum: 
      name: "{{ packages }}" 
      state: present
    vars:
      packages:
#     - libselinux-python
      - pv
    when: ansible_os_family == "RedHat"

  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml
