---
# This playbook tests the PS-5.6 upgrade 

- hosts: all
  become: true
  become_method: sudo

  tasks:
  # Add an Apt signing key, will not download if present
  - apt_key: id=CD2EFD2A keyserver=keys.gnupg.net state=present
    when: ansible_os_family == "Debian"

  - name: add the deb repo
    apt_repository: repo='deb [arch=amd64] http://192.168.88.9/apt {{ansible_lsb.codename}} main' state=present update_cache=yes
 #   apt_repository: repo='deb http://repo.percona.com/apt {{ansible_lsb.codename}} main testing' state=present update_cache=yes
    when: ansible_os_family == "Debian"

  - name: add the yum percona repos 
    yum: name=https://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 6

  - name: epel 6 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: epel 7 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present 
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install deb packages 
    apt: name={{item}} update_cache=yes
    with_items: 
    - vim
    - pv
    - aptitude
    - percona-server-server-5.6
    - percona-xtrabackup
    - sysbench
    - percona-toolkit
    - percona-server-test-5.6
    - percona-server-5.6-dbg
    - percona-server-source-5.6
    - percona-server-tokudb-5.6
    when: ansible_os_family == "Debian"

  - name: install packages in centos
    yum: name={{item}} state=present #enablerepo=percona-testing-x86_64
    with_items:
    - libselinux-python
    - pv
    - sysbench
    - Percona-Server-server-56
    - Percona-Server-test-56
    - Percona-Server-56-debuginfo
    - Percona-Server-devel-56
    - Percona-Server-tokudb-56
    - percona-toolkit
    - percona-xtrabackup
    when: ansible_os_family == "RedHat"

  - name: start mysql service with init scrip
    command: /etc/init.d/mysql start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

  - name: start mysql service with service command
    command: service mysql start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mysql service with systemd
    command: systemctl start mysql
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install tokudb
    command: /usr/bin/ps_tokudb_admin --enable

  - name: install tokubackup
    command: /usr/bin/ps_tokudb_admin --enable-backup
    when: ansible_os_family == "Debian"

  - service: name=mysql state=restarted
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

  - service: name=mysql state=restarted
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - service: name=mysqld state=restarted
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - service: name=mysql state=restarted
    when: ansible_os_family == "Debian"

  - name: install tokudb
    command: /usr/bin/ps_tokudb_admin --enable
 
  - name: install tokubackup
    command: /usr/bin/ps_tokudb_admin --enable-backup
    when: ansible_os_family == "Debian"

  - name: install plugins
    command: /vagrant/plugins_test_56.sh

  - name: install 3rd party packages
    apt: name={{item}}
    with_items:
    - rsyslog-mysql
    when: ansible_os_family == "Debian"

  - name: remove the Percona apt main repository
    apt_repository: repo='deb [arch=amd64] http://192.168.88.9/apt {{ ansible_lsb.codename }} main' state=absent update_cache=yes
    when: ansible_os_family == "Debian"

  - name: enable deb testing repos
    apt_repository: repo='deb [arch=amd64] http://192.168.88.9/apt {{ansible_lsb.codename}} main testing' state=present update_cache=yes
    when: ansible_os_family == "Debian" 

  - name: run upgrade on Debian/Ubuntu
    apt: upgrade=yes
    when: ansible_os_family == "Debian" 
    
  - name: upgrade Percona Server to new rpm packages
    yum: name={{item}} state=latest enablerepo=percona-testing-x86_64
    with_items:
    - Percona-Server-server-56
    - Percona-Server-test-56
    - Percona-Server-56-debuginfo
    - Percona-Server-devel-56
    - Percona-Server-tokudb-56
    when: ansible_os_family == "RedHat"

  - name: run mysql_upgrade for CentOS
    command: mysql_upgrade
    when: ansible_os_family == "RedHat"

  - name: check that Percona Server 5.6 version is correct
    command: /vagrant/version_check.sh ps56

  - name: running sysbench
    command: /vagrant/sb.sh
