---
# This playbook sets up the percona repo

- hosts: all
  become: true
  become_method: sudo

  tasks:

  - name: include tasks for test env setup
    include: ../tasks/test_prep.yml

  - name: include tasks for enabling test repo
    include: ../tasks/enable_testing_repo.yml
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: include tasks for enabling main repo
    include: ../tasks/enable_main_repo.yml
    when: lookup('env', 'install_repo') == "main"

  - name: install deb packages 
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars: 
      packages:
      - vim
      - sysbench
      - sysbench-tpcc
      - pv
      - percona-server-server-5.6
      - percona-xtrabackup
      - percona-xtrabackup-test
      - percona-xtrabackup-dbg
      - percona-toolkit
      - percona-server-test-5.6
      - percona-server-5.6-dbg
      - percona-server-source-5.6
      - percona-server-tokudb-5.6
    when: ansible_os_family == "Debian"

  - name: install packages in centos
    yum: 
      name: "{{ packages }}" 
      state: present 
      enablerepo: percona-testing-x86_64
    vars:
      packages:
      - libselinux-python
      - sysbench
      - sysbench-tpcc
      - Percona-Server-server-56
      - Percona-Server-test-56
      - Percona-Server-56-debuginfo
      - Percona-Server-devel-56
      - Percona-Server-tokudb-56
      - Percona-Server-selinux-56
      - percona-toolkit
      - percona-xtrabackup
      - percona-xtrabackup-test
      - percona-xtrabackup-debuginfo
    when: ansible_os_family == "RedHat"

  # Enable SELinux on CentOS
  - selinux:
      policy: targeted
      state: enforcing
    when: ansible_os_family == "RedHat"

  - name: use service to start mysql
    command: service mysql start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: use systmectl to start mysql
    command: systemctl start mysql
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install tokudb
    command: /usr/bin/ps_tokudb_admin --enable-backup

  - name: restart mysql service RHEL 7
    service: name=mysqld state=restarted
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: restart mysql service RHEL 6
    service: name=mysql state=restarted
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: restart mysql service on Devian/Ubuntu
    service: name=mysql state=restarted
    when: ansible_os_family == "Debian"

  - name: install tokudb
    command: /usr/bin/ps_tokudb_admin --enable-backup

  - name: install plugins
    command: /vagrant/plugins_test_56.sh

  - name: version check
    command: /vagrant/version_check.sh ps56

  - name: sysbench version check
    command: /vagrant/version_check.sh sysbench

  - name: Percona Server 5.6 package version check
    command: /vagrant/package_check.sh ps56

  - name: PXB-2.3 package version check
    command: /vagrant/package_check.sh pxb23

  - name: run sysbench tpcc prepare script
    command: /usr/share/sysbench/tpcc.lua --mysql-user=root --mysql-db=sbt --time=30 --threads=64 --report-interval=1 --tables=3 --scale=5 --db-driver=mysql prepare

  - name: run sysbench tpcc benchmark
    command: /usr/share/sysbench/tpcc.lua --mysql-user=root --mysql-db=sbt --time=30 --threads=64 --report-interval=1 --tables=3 --scale=5 --db-driver=mysql run
