---
# This playbook tests PS-5.5 installs

- hosts: all
  become: true
  become_method: sudo

  tasks:

  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_0.1-5.{{ansible_lsb.codename}}_all.deb
    when: ansible_os_family == "Debian"

  - name: add the deb repo
    apt_repository: repo='deb http://repo.percona.com/apt {{ansible_lsb.codename}} main testing' state=present update_cache=yes
    when: ansible_os_family == "Debian"

  # Enable SELinux on CentOS
# - selinux: 
#     policy: targeted
#     state: enforcing
#   when: ansible_os_family == "RedHat"

  - name: add the yum percona repos 
    yum: name=https://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 6

  - name: epel 6 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: epel 7 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present 
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install deb packages 
    apt: name={{item}} update_cache=yes
    with_items: 
    - vim
    - percona-server-server-5.5
    - percona-xtrabackup
    - percona-toolkit
    - percona-server-test-5.5
    - percona-server-5.5-dbg
    - percona-server-source-5.5
#   - percona-nagios-plugins
#   - percona-cacti-templates
#   - percona-zabbix-templates
    - sysbench
    when: ansible_os_family == "Debian"

  - name: install packages in centos
    yum: name={{item}} state=present enablerepo=percona-testing-x86_64
    with_items:
    - libselinux-python
    - Percona-Server-server-55
    - Percona-Server-test-55
    - Percona-Server-55-debuginfo
    - Percona-Server-devel-55
    - percona-toolkit
    - percona-xtrabackup
    - percona-zabbix-templates
    - percona-nagios-plugins
    - sysbench
    - percona-cacti-templates
    when: ansible_os_family == "RedHat"

  - name: use service to start mysql
    command: service mysql start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: use systemctl to start mysql
    command: systemctl start mysql
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install plugins
    command: /vagrant/plugins_test_55.sh

  - name: install 3rd party packages
    apt: name={{item}}
    with_items:
    - rsyslog-mysql
    when: ansible_os_family == "Debian"

  - name: run version_check
    command: /vagrant/version_check.sh ps55

  - name: run package test
    command: /vagrant/package_check.sh ps55

  - name: check that Percona Toolkit version is correct
    command: /vagrant/version_check.sh pt

  - name: check that sysbench version is correct
    command: /vagrant/version_check.sh sysbench

