---
# This playbook sets up the mongodb-org repo and installs mongodb

- hosts: all
  become: true
  become_method: sudo

  tasks:
  # Add the mongodb apt signing key, will not download if present
  - apt_key: id=0C49F3730359A14518585931BC711F9BA15703C6 keyserver=keyserver.ubuntu.com state=present
    when: ansible_os_family == "Debian"

  - name: add the mongo ubuntu repo
    apt_repository: repo='deb https://repo.mongodb.org/apt/ubuntu {{ansible_lsb.codename}}/mongodb-org/3.4 multiverse' state=present update_cache=yes
    when: ansible_distribution == "Ubuntu"

  - name: add the mongo debian repo
    apt_repository: repo='deb http://repo.mongodb.org/apt/debian {{ansible_lsb.codename}}/mongodb-org/3.4 main' state=present update_cache=yes
    when: ansible_distribution == "Debian"
  # Add the Percona apt signing key, will not download if present

  - name: install EPEL repos
    include: ../tasks/epel_repos.yml  

  - name: install deb packages 
    apt: name={{item}} update_cache=yes
    with_items: 
    - vim
    - pv
    - mongodb-org
    when: ansible_os_family == "Debian"

  - name: Install percona repository package for Debian/Ubuntu
    apt:
      deb: https://repo.percona.com/apt/percona-release_0.1-4.{{ansible_lsb.codename}}_all.deb
    when: ansible_os_family == "Debian"
