---
# This playbook sets up the oracle mysql repo and installs the MySQL repo

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: Download the deb repo package from oracle
    command: wget http://dev.mysql.com/get/mysql-apt-config_0.5.3-1_all.deb 
    when: ansible_os_family == "Debian"
  - name: Download the rpm repo package from oracle
    command: wget http://dev.mysql.com/get/mysql57-community-release-el5-7.noarch.rpm
    when: ansible_os_family == "RedHat"
