---
# This playbook tests PS-5.5 installs

- hosts: all
  become: true
  become_method: sudo

  tasks:

  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_0.1-4.{{ansible_lsb.codename}}_all.deb
    when: ansible_os_family == "Debian"

  - name: add the deb repo
    apt_repository: repo='deb http://repo.percona.com/apt {{ansible_lsb.codename}} main' state=present update_cache=yes
    when: ansible_os_family == "Debian"

  - name: add the yum percona repos 
    yum: name=https://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 6

  - name: epel 6 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: epel 7 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present 
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install deb packages  
    apt: name={{item}} update_cache=yes
    with_items: 
    - vim
    - proxysql
    when: ansible_os_family == "Debian"

  - name: install packages in centos
    yum: name={{item}} state=present
    with_items:
    - libselinux-python
    - proxysql
    when: ansible_os_family == "RedHat"

  - name: start proxysql service
    service: name=proxysql state=started

  - name: enable deb testing repos
    apt_repository: repo='deb http://repo.percona.com/apt {{ansible_lsb.codename}} main testing' state=present update_cache=yes
    when: ansible_os_family == "Debian"

  - name: run upgrade on Debian/Ubuntu
    apt: upgrade=yes
    when: ansible_os_family == "Debian"

  - name: upgrade Percona Server to new rpm packages
    yum: name={{item}} state=latest enablerepo=percona-testing-x86_64
    with_items:
    - proxysql
    when: ansible_os_family == "RedHat"

  - name: run version_check
    command: /vagrant/version_check.sh proxysql

  - name: check if service is running after upgrade
    command: /vagrant/proxy_check.sh

  - name: stop proxysql service
    service: name=proxysql state=stopped

  - name: start proxysql service
    service: name=proxysql state=started
