---
# This playbook does following:
#   sets main Percona repo
#   installs PS 5.6, PT and PXB 2.3
#   changes repo to testing
#   upgrades packages to the new version
#   does some tests

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: include tasks for test env setup
    include: ../tasks/test_prep.yml

#
# Install from main repository
#
  - name: include tasks for enabling main repo
    include: ../tasks/enable_main_repo.yml

  - name: download and extract world database
    command: "{{ item }}"
    with_items:
    - wget --no-check-certificate -P /package-testing https://raw.githubusercontent.com/Percona-QA/percona-qa/master/sample_db/world.sql

  - name: install Percona Server deb packages previous version
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - percona-server-server-5.6
    - percona-server-test-5.6
    - percona-server-5.6-dbg
    - percona-server-source-5.6
    - percona-server-tokudb-5.6
    when: ansible_os_family == "Debian"

  - name: install Percona Toolkit deb packages previous version
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - percona-toolkit
    when: ansible_os_family == "Debian"

  - name: install sysbench deb packages previous version
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - sysbench
    when: ansible_os_family == "Debian"

  - name: install Percona XtraBackup deb packages previous version
    apt: name={{item}} update_cache=no state=latest
    with_items:
    - percona-xtrabackup
    - percona-xtrabackup-test
    - percona-xtrabackup-dbg
    when: ansible_os_family == "Debian"

  - name: install Percona Server rpm packages previous version
    yum: name={{item}} state=latest
    with_items:
    - Percona-Server-server-56
    - Percona-Server-test-56
    - Percona-Server-56-debuginfo
    - Percona-Server-devel-56
    - Percona-Server-tokudb-56
    - Percona-Server-shared-56
    - Percona-Server-client-56
    when: ansible_os_family == "RedHat"

  - name: install Percona Toolkit rpm packages previous version
    yum: name={{item}} state=latest
    with_items:
    - percona-toolkit
    when: ansible_os_family == "RedHat"

  - name: install sysbench rpm packages previous version
    yum: name={{item}} state=latest
    with_items:
    - sysbench
    when: ansible_os_family == "RedHat"

  - name: install Percona XtraBackup rpm packages previous version
    yum: name={{item}} state=latest
    with_items:
    - percona-xtrabackup
    - percona-xtrabackup-test
    - percona-xtrabackup-debuginfo
    when: ansible_os_family == "RedHat"

  - name: start mysql service with init script
    command: /etc/init.d/mysql start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

  - name: start mysql service with service command
    command: service mysql start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mysql service with systemctl command
    command: systemctl start mysql
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

# - name: disable selinux on centos7 for TokuDB to work
#   command: setenforce 0
#   when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install tokudb and restart server
    command: /usr/bin/ps_tokudb_admin --enable 

  - name: restart mysql service
    service: name=mysql state=restarted

  - name: re-run ps_tokudb_admin to finish tokudb install
    command: /usr/bin/ps_tokudb_admin --enable 

  - name: install plugins, import world database, test tokudb
    command: /package-testing/plugins_test_56.sh ps

  - name: install 3rd party packages with apt
    apt: name={{item}}
    with_items:
    - rsyslog-mysql
    when: ansible_os_family == "Debian"

  - name: install 3rd party packages with yum
    yum: name={{item}}
    with_items:
    - rsyslog-mysql
    when: ansible_os_family == "RedHat"

# Start PAM test
  - group:
      name: developer
      state: present

  - group:
      name: dbadmin
      state: present

  - user:
      name: test_pam
      shell: /bin/bash
      password: $6$mrqBDJUyh13p$elUkdb99/v4fPxnLIS2TAXSUhVt16PvOvIPzVqobKKZKHHMRyXOmJ4puhybn0Go0HpL1RNYvREgqF02qYnGOX1

  - user:
      name: test_pam2
      shell: /bin/bash
      password: $6$mrqBDJUyh13p$elUkdb99/v4fPxnLIS2TAXSUhVt16PvOvIPzVqobKKZKHHMRyXOmJ4puhybn0Go0HpL1RNYvREgqF02qYnGOX1
      groups: developer
      append: yes

  - user:
      name: test_pam3
      shell: /bin/bash
      password: $6$mrqBDJUyh13p$elUkdb99/v4fPxnLIS2TAXSUhVt16PvOvIPzVqobKKZKHHMRyXOmJ4puhybn0Go0HpL1RNYvREgqF02qYnGOX1
      groups: dbadmin
      append: yes

  - user:
      name: test_pam_compat
      shell: /bin/bash
      password: $6$mrqBDJUyh13p$elUkdb99/v4fPxnLIS2TAXSUhVt16PvOvIPzVqobKKZKHHMRyXOmJ4puhybn0Go0HpL1RNYvREgqF02qYnGOX1

  - user:
      name: mysql
      groups: shadow
      append: yes
    when: ansible_os_family == "Debian"

  - file:
      path: /etc/shadow
      group: mysql
      mode: "g+r"
    when: ansible_os_family == "RedHat"

  - name: copy config file for mysql PAM into system dir
    template:
      src: ../scripts/ps_pam_test/mysqld
      dest: /etc/pam.d/mysqld
      owner: root
      group: root
      mode: 0644
      force: yes

  - name: restart mysql service
    service: name=mysql state=restarted

  - name: run mysql setup for PAM
    command: /usr/local/bin/bats /package-testing/scripts/ps_pam_test/ps_pam_mysql_setup.bats
# End PAM test

#
# Enable testing repository
#
  - include: ../tasks/enable_testing_repo.yml

#
# Upgrade packages
#
  - name: upgrade Percona Toolkit to new deb packages
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - percona-toolkit
    when: ansible_os_family == "Debian"

  - name: upgrade Percona Server to new deb packages
    apt: name={{item}} update_cache=no state=latest
    with_items:
    - percona-server-server-5.6
    - percona-server-test-5.6
    - percona-server-5.6-dbg
    - percona-server-source-5.6
    - percona-server-tokudb-5.6
    when: ansible_os_family == "Debian"

  - name: upgrade Percona XtraBackup to new deb packages
    apt: name={{item}} update_cache=no state=latest
    with_items:
    - percona-xtrabackup
    - percona-xtrabackup-test
    - percona-xtrabackup-dbg
    when: ansible_os_family == "Debian"

  - name: upgrade Percona Toolkit to new rpm packages
    yum: name={{item}} state=latest
    with_items:
    - percona-toolkit
    when: ansible_os_family == "RedHat"

  - name: upgrade Percona Server to new rpm packages
    yum: name={{item}} state=latest
    with_items:
    - Percona-Server-server-56
    - Percona-Server-test-56
    - Percona-Server-56-debuginfo
    - Percona-Server-devel-56
    - Percona-Server-tokudb-56
    - Percona-Server-shared-56
    - Percona-Server-client-56
    - Percona-Server-selinux-56
    when: ansible_os_family == "RedHat"

  - name: upgrade Percona XtraBackup to new rpm packages
    yum: name={{item}} state=latest
    with_items:
    - percona-xtrabackup
    - percona-xtrabackup-test
    - percona-xtrabackup-debuginfo
    when: ansible_os_family == "RedHat"

  - name: run mysql_upgrade
    command: mysql_upgrade -uroot
    when: ansible_os_family == "RedHat"

  - name: restart mysql service on centos 5
    command: /etc/init.d/mysql restart
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

  - name: restart mysql service
    service: name=mysql state=restarted
    when: ansible_os_family != "RedHat" or ansible_distribution_major_version != "5"

  - name: check that Percona Server version is correct
    command: /package-testing/version_check.sh ps56

  - name: check that Percona Server package versions are correct
    command: /package-testing/package_check.sh ps56

  - name: check that Percona Toolkit version is correct
    command: /package-testing/version_check.sh pt

  - name: check that Percona XtraBackup version is correct
    command: /package-testing/version_check.sh pxb23

  - name: check that Percona XtraBackup package versions are correct
    command: /package-testing/package_check.sh pxb23

  - name: run bats tests for PAM
    command: /usr/local/bin/bats /package-testing/scripts/ps_pam_test/ps_pam_test.bats

  - name: run bats unit tests for ps_tokudb_admin scripts
    command: /usr/local/bin/bats /package-testing/bats/ps_tokudb_admin_unit.bats

  - name: run bats integration tests for ps_tokudb_admin script
    command: /usr/local/bin/bats /package-testing/bats/ps_tokudb_admin_integration.bats

  - name: run bats tests for mysql init scripts
    command: /usr/local/bin/bats /package-testing/bats/mysql-init-scripts.bats

  - name: start mysql service
    service: name=mysql state=started

  - name: uninstall PAM before final package uninstall
    command: /usr/local/bin/bats /package-testing/scripts/ps_pam_test/ps_pam_mysql_uninstall.bats

  - name: remove Percona Server deb packages
    apt: name={{item}} update_cache=no state=absent
    with_items:
    - percona-server-server-5.6
    when: ansible_os_family == "Debian"

  - name: remove Percona Server rpm packages
    yum: name={{item}} state=absent
    with_items:
    - Percona-Server-server-56
    when: ansible_os_family == "RedHat"

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mysql stopped
