---
# This playbook sets up the percona repo

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: add the yum percona repos 
    yum: name=https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    when: ansible_os_family == "RedHat" 

  - name: epel 6 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: epel 7 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

  - name: download and extract world database
    command: "{{ item }}"
    with_items:
    - wget --no-check-certificate -P /package-testing https://raw.githubusercontent.com/Percona-QA/percona-qa/master/sample_db/world.sql

  - name: install packages in centos
    yum: 
      name: "{{ packages }}" 
      state: present 
    vars:
      packages:
      - libselinux-python
      - pv
      - unzip
    when: ansible_os_family == "RedHat"

  - name: enable ps-80 repos 
    command: percona-release enable-only ps-80 testing

  - name: enable tools repos 
    command: percona-release enable tools testing

  - name: install deb packages 
    apt: 
      name: "{{ packages }}" 
      update_cache: yes
    vars:
      packages:
      - vim
      - pv
      - unzip
      - sysbench
    when: ansible_os_family == "Debian"

  - name: install deb packages 
    apt: 
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - percona-toolkit
      - percona-server-server
      - percona-server-test
      - percona-server-source
      - percona-server-tokudb
      - percona-server-rocksdb
      - percona-xtrabackup-test-80
      - percona-xtrabackup-dbg-80
      - percona-xtrabackup-80
      - sysbench
      - sysbench-tpcc
    when: ansible_os_family == "Debian"

  - name: install packages in centos
    yum: 
      name: "{{ packages }}" 
      state: present #enablerepo=percona-experimental-x86_64 
    vars:
      packages:
      - percona-server-server
      - percona-server-test
      - percona-server-debuginfo
      - percona-server-devel
      - percona-server-tokudb
      - percona-server-rocksdb
      - percona-toolkit
      - percona-xtrabackup-80
      - percona-xtrabackup-test-80
      - percona-xtrabackup-80-debuginfo
      - sysbench
      - sysbench-tpcc
    when: ansible_os_family == "RedHat"

  - name: install latest bats from github
    command: "{{ item }}"
    with_items:
    - rm -f master.zip
    - wget --no-check-certificate -O master.zip https://github.com/sstephenson/bats/archive/master.zip
    - unzip master.zip
    - rm -f master.zip
    - bats-master/install.sh /usr/local
    - rm -rf bats-master

  - service: name=mysql state=started
#   when: ansible_os_family == "RedHat"

# - name: copy group replication settings
#   template: src=../templates/group_replication.j2
#             dest=/etc/mysql/percona-server.conf.d/gr.cnf
#   when: ansible_os_family == "Debian"

  - name: set root password
    command: /vagrant/setpass_57.sh
    when: ansible_os_family == "RedHat"

  - name: install tokudb
    command: /usr/bin/ps-admin --enable-tokudb

  - name: install tokubackup
    command: /usr/bin/ps-admin --enable-tokubackup

  - service: name=mysql state=restarted
    when: ansible_os_family == "RedHat"

  - service: name=mysql state=restarted
    when: ansible_os_family == "Debian"

  - name: install tokudb
    command: /usr/bin/ps-admin --enable-tokubackup

  - name: install rocksdb
    command: /usr/bin/ps-admin --enable-rocksdb

  - name: install plugins
    command: /vagrant/plugins_test_80.sh ps

  - name: version check
    command: /vagrant/version_check.sh ps80

  - name: Percona Server 8.0 package version check
    command: /vagrant/package_check.sh ps80
