---
# This playbook sets up the mongodb-org repo and installs mongodb

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: include tasks for test env setup
    include: ../tasks/test_prep.yml

# - name: include tasks for enabling test repo
#   include: ../tasks/enable_testing_repo.yml

  - name: install deb packages 
    apt: name={{item}} update_cache=yes
    with_items: 
    - vim
    - percona-server-mongodb-32
    - percona-server-mongodb-32-dbg
    when: ansible_os_family == "Debian"

  - name: epel 6 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: epel 7 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: add the yum percona repos
    yum: name=http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 6 

  - name: install packages in centos
    yum: name={{item}} state=present enablerepo=percona-testing-x86_64
    with_items:
    - redhat-lsb
    - libselinux-python
    - Percona-Server-MongoDB-32
    - Percona-Server-MongoDB-32-debuginfo
    when: ansible_os_family == "RedHat"

  - command: service mongod start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - command: systemctl start mongod
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: run psmdb_test
    command: /vagrant/psmdb_test.sh 3.2

  - name: run package_test
    command: /vagrant/package_check.sh psmdb32

