---
# This playbook sets up the percona repo

- hosts: all
  become: true
  become_method: sudo

  tasks:
  # Add an Apt signing key, will not download if present
  - apt_key: id=CD2EFD2A keyserver=keys.gnupg.net state=present
    when: ansible_os_family == "Debian"
  - apt_key: id=8507EFA5 keyserver=keys.gnupg.net state=present
    when: ansible_os_family == "Debian"

  - name: add the deb repo
    apt_repository: repo='deb http://repo.percona.com/apt {{ansible_lsb.codename}} main testing' state=present update_cache=yes
    when: ansible_os_family == "Debian"

  - name: add the yum percona repos 
    yum: name=http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 6

  - name: epel 6 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: epel 7 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install deb packages 
    apt: name={{item}} update_cache=yes
    with_items: 
    - vim
    - sysbench
    - pv
    - percona-server-server-5.6
    - percona-xtrabackup
    - percona-xtrabackup-test
    - percona-xtrabackup-dbg
    - percona-toolkit
    when: ansible_os_family == "Debian"

  - name: install packages in centos
    yum: name={{item}} state=present enablerepo=percona-testing-x86_64
    with_items:
    - libselinux-python
    - sysbench
    - Percona-Server-server-56
    - percona-toolkit
    - percona-xtrabackup
    - percona-xtrabackup-test
    - percona-xtrabackup-debuginfo
    when: ansible_os_family == "RedHat"

  - command: /etc/init.d/mysql start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

  - command: service mysql start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - command: systemctl start mysql
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install plugins
    command: /vagrant/plugins_test_55.sh

  - name: PXB-2.3 package version check
    command: /vagrant/package_check.sh pxb23

  - name: running sysbench
    command: /vagrant/sb.sh

  - name: run backup
    command: /usr/bin/xtrabackup --backup --user=root --target-dir=/tmp/backups/

  - name: prepare backup
    command: /usr/bin/xtrabackup --prepare --target-dir=/tmp/backups/
