---
# This playbook sets up the garbd 

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_0.1-4.{{ansible_lsb.codename}}_all.deb
    when: ansible_os_family == "Debian"

  - name: add the repo
    apt_repository: repo='deb http://repo.percona.com/apt {{ansible_lsb.codename}} main testing' state=present
  # Add an Apt signing key, will not download if present
  - name: install garbd
    apt: name={{ item }} update_cache=yes
    with_items: 
    - vim
    - pv
    - python-mysqldb
    - percona-xtradb-cluster-garbd-5.7
  - name: configure garbd
    template: src=../templates/garbd.j2 
              dest=/etc/default/garbd
              mode=0640 owner=root group=root
  # start garbd service
  - command: service garbd start
  
