---
# This playbook sets up the garbd 

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - apt_key: id=CD2EFD2A keyserver=keys.gnupg.net state=present
  - apt_key: id=8507EFA5 keyserver=keys.gnupg.net state=present
  - name: add the repo
    apt_repository: repo='deb http://repo.percona.com/apt {{ansible_lsb.codename}} main testing' state=present
  # Add an Apt signing key, will not download if present
  - name: install garbd
    apt: name={{ item }} update_cache=yes
    with_items: 
    - vim
    - pv
    - python-mysqldb
    - percona-xtradb-cluster-garbd-5.7
  - name: configure garbd
    template: src=../templates/garbd.j2 
              dest=/etc/default/garbd
              mode=0640 owner=root group=root
  # start garbd service
  - command: service garbd start
  
