---
# This playbook sets up the pxc

- hosts: all
  become: true
  become_method: sudo

  tasks:
 
# - debug: var=ansible_all_ipv4_addresses
  - set_fact:
      man_ip: "{{ item }}"
    with_items: "{{ ansible_all_ipv4_addresses }}"
    when: "item.startswith('192.168')"
# - debug: var=man_ip
 
  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_0.1-6.{{ansible_lsb.codename}}_all.deb
    when: ansible_os_family == "Debian" 

  - name: add the testing repo
    apt_repository: repo='deb http://repo.percona.com/apt {{ansible_lsb.codename}} main testing' state=present

  - name: install galera, vim, pv, python-mysqldb, pxc-56
    apt: 
      name: "{{ packages }}"
      update_cache: yes
    vars: 
      packages:
      - sysbench
      - vim
      - pv
      - python-mysqldb
      - percona-xtradb-cluster-56

  - name: stop mysql service
    service: name=mysql pattern=/usr/bin/mysqld_safe state=stopped 

  - name: configure PXC
    template: src=../templates/my.j2 
              dest=/etc/mysql/my.cnf
              mode=0640 owner=mysql group=root

  - name: start mysql service
    command: service mysql start

  - name: version check
    command: /vagrant/version_check.sh pxc56

# commented out until https://jira.percona.com/browse/BLD-935 is fixed
# - name: mysqladmin shutdown test
#   command: /vagrant/madmin_check.sh
