---
# This playbook sets up the garbd 

- hosts: all
  become: true
  become_method: sudo

  tasks:

  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_0.1-4.{{ansible_lsb.codename}}_all.deb
    when: ansible_os_family == "Debian"

  - name: add the repo
    apt_repository: repo='deb [arch=amd64] http://repo.percona.com/apt {{ansible_lsb.codename}} main testing' state=present
  - name: install garbd
    apt: name={{ item }} update_cache=yes
    with_items: 
#   - language-pack-hr
    - vim
    - pv
    - proxysql
