---
# This playbook can be used to setup machine for running tests and ansible
# Therefore gathering of the facts is disabled

- hosts: all
  become: true
  become_method: sudo
  gather_facts: false
  
  tasks:
# - name: check RH version
#   shell: grep -c 8 /etc/redhat-release
#   register: result

  - name: Download the RHEL 8 dev-repo
    get_url:
      url: https://jenkins.percona.com/yum-repo/rhel8/rhel8-beta.repo
      dest: /etc/yum.repos.d/percona-dev.repo
      mode: 0440
#   when: result == "1"

  - name: install python
    raw: test -e /usr/bin/python || (which apt && apt -y update && apt install -y python-minimal) || (which dnf && dnf install -y python3)
