---
# This playbook sets up the percona repo

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: add the deb repo
    apt_repository: repo='deb [arch=amd64] http://192.168.88.9/apt {{ansible_lsb.codename}} main testing' state=present
    when: ansible_os_family == "Debian"
  - name: upgrade deb packages 
    apt: update_cache=yes upgrade=safe
    when: ansible_os_family == "Debian"
  - name: upgrade packages in centos
    yum: name=Percona-Server-server-55 enablerepo=percona-testing-x86_64 state=latest
    when: ansible_os_family == "RedHat"
